# Series of queries that I frequently use in R which connect to 
# ADV database and pull out xyz

# Address Table in parts
# First part is basics, 2nd part is all else, turn on off by add/remove dashes
address_data <- sqlQuery(squibbs, "( SELECT DISTINCT 
  a.ID_NUMBER ,a.XSEQUENCE ,a.ADDR_TYPE_CODE ,a.ADDR_STATUS_CODE ,a.ADDR_PREF_IND
  ,a.STREET1 ,a.STREET2 ,a.STREET3 ,a.FOREIGN_CITYZIP ,a.CITY ,a.STATE_CODE ,a.ZIPCODE
  ,a.START_DT as ADDR_START_DT ,a.STOP_DT AS ADDR_STOP_DT ,a.XCOMMENT AS XCOMMENT_ADDR 
  ,a.DATE_ADDED AS ADDR_ADD_DT ,a.DATE_MODIFIED AS ADDR_MOD_DT ,a.OPERATOR_NAME AS ADDR_OPERATOR
  ,RANK() OVER (PARTITION BY a.id_number ORDER BY a.date_added DESC, rownum) AS rnk 
  
  --,a.ADDR_CONTROL ,a.CARE_OF ,a.COMPANY_NAME_1 ,a.COMPANY_NAME_2 ,a.BUSINESS_TITLE
  --,a.ZIP_SUFFIX ,a.POSTNET_ZIP ,a.COUNTY_CODE ,a.COUNTRY_CODE ,a.ADDRESS_MOD_DATE
  --,a.MAIL_RETURNED_CODE ,a.MAIL_RETURNED_NBR ,a.MAIL_RETURNED_DATE ,a.TRACER_SENT_DATE ,a.PERSON_RESP_ID_NUMBER 
  --,a.EMPLOY_STOP_DT ,a.EMPLOY_SEQUENCE ,a.ADDR_SRC_CODE ,a.CHANGE_SOURCE_CODE ,a.SRC_ID_NUMBER
  --,a.USE_FOR_TAX_RECEIPT_IND ,a.ADDR_VERIFIED_CODE ,a.ADDRESS_CODE ,a.LINE_1 ,a.LINE_2
  --,a.LINE_3 ,a.LINE_4 ,a.LINE_5 ,a.LINE_6 ,a.LINE_7 ,a.LINE_8 ,a.USER_GROUP 
  --,a.LOCATION_ID ,a.LATITUDE ,a.LONGITUDE ,a.GEOCODE_GEOMETRY ,a.GEOCODE_ADDRESS
  FROM advance.address a  )")


# Entity table in parts
# First part is basics, 2nd is mail codes, 3rd is marital/joint, 4th is all else
# Turn on/off lines by adding/removing dashes
entity_data <- sqlQuery(squibbs, "( SELECT 
  e.ID_NUMBER ,e.FIRST_NAME ,e.MIDDLE_NAME ,e.LAST_NAME ,e.PERSON_OR_ORG 
  ,e.RECORD_TYPE_CODE ,e.RECORD_STATUS_CODE ,e.STATUS_CHANGE_DATE ,e.PREF_ADDR_TYPE_CODE 
  ,e.BIRTH_DT ,e.GENDER_CODE ,e.DATE_ADDED ,e.DATE_MODIFIED ,e.OPERATOR_NAME
  
  --,e.SOLICIT_CTRL_CODE ,e.SOLICIT_CTRL_CHNG_DATE ,e.SOLICIT_CTRL_DATE
  --,e.SOLICIT_CTRL_COMMENT ,e.ALUM_MAG_MAIL_CODE ,e.MAIL_CODE1 ,e.MAIL_CODE2
  --,e.MAIL_CODE3 ,e.MAIL_CODE4 ,e.MAIL_CODE5 ,e.MAIL_CODE6 ,e.MAIL_CODE7
  --,e.MAIL_CODE8 ,e.MAIL_CODE9 ,e.MAIL_CODE10
  
  --,e.MARITAL_STATUS_CODE ,e.JNT_ADDRESS_IND ,e.JNT_MAILINGS_IND ,e.JNT_GIFTS_IND 
  --,e.JNT_TELEPHONE_IND ,e.PREF_JNT_MAIL_NAME1 ,e.PREF_JNT_MAIL_NAME2 ,e.MARITAL_STATUS_CHG_DT
  --,e.MARITAL_COMMENT ,e.MARITAL_SRC_CODE ,e.SPOUSE_STATUS_CODE ,e.SPOUSE_NAME
  --,e.SPOUSE_ID_NUMBER ,e.SPOUSE_SALUTATION ,e.SPOUSE_NICKNAME ,e.SPOUSE_BIRTH_DT
  --,e.MARRIAGE_PLACE ,e.MARRIAGE_DT ,e.MARRIAGE_ALUM_MAG_DATE ,e.JNT_SALUTATION  

  --,e.RELATIONS_NBR ,e.QUESTION_RETURN_DATE ,e.CLASS_AGT_CODE ,e.XCOMMENT ,e.PREF_MAIL_NAME
  --,e.REPORT_NAME ,e.ENTITY_SRC_CODE ,e.PREF_NAME_SORT ,e.NAME_CHANGE_DATE ,e.DIRECTORIES_NBR
  --,e.DELETE_IND ,e.DELETE_MODIFIED_DATE ,e.DELETE_OPERATOR ,e.PREF_CLASS_YEAR ,e.PREF_SCHOOL_CODE
  --,e.PERS_SUFFIX ,e.PROF_SUFFIX ,e.INSTITUTIONAL_SUFFIX ,e.PREFIX ,e.SALUTATION ,e.ETHNIC_CODE
  --,e.RELIGION_CODE ,e.LANGUAGE_PREFERENCE_CODE ,e.BIRTH_PLACE ,e.CHILDREN_NBR ,e.DEATH_DT
  --,e.DEATH_NOTIFIED_DATE ,e.DEATH_CONFIRMED_DATE ,e.DEATH_PLACE ,e.DEATH_LETTER_DATE1
  --,e.DEATH_LETTER_DATE2 ,e.DEATH_OBIT_CODE ,e.DEATH_ALUM_MAG_DATE ,e.CITIZEN_CNTRY_CODE1
  --,e.CITIZEN_CNTRY_CODE2 ,e.ORG_LONG_NAME1 ,e.ORG_LONG_NAME2 ,e.CUSIP_CODE ,e.CASE_CODE
  --,e.MATCHING_RATIO_CODE ,e.HOLDINGS_SIZE_CODE ,e.ETHNIC_SRC_CODE ,e.POLITICAL_INTEREST_CODE
  --,e.EMPLOYEE_FULL_TIME_CNT ,e.EMPLOYEE_PART_TIME_CNT ,e.LAST_RESEARCH_DT ,e.INCORPORATION_DT
  --,e.VIP_IND ,e.YR_END_RCPT_REQUESTED_IND ,e.YR_END_RCPT_START_DATE ,e.YR_END_RCPT_STOP_DATE
  --,e.USER_GROUP ,e.LOCATION_ID ,e.GROUP_ID ,e.MAIL_CHANGE_SOURCE ,e.MARITAL_CHANGE_SOURCE
  --,e.PRIMARY_SPOUSE_ENTITY_IND  
  FROM advance.entity e )")

phone_data <- sqlQuery(squibbs, "(
SELECT *
  FROM advance.telephone)")

# Pulls out data for names, IE to check to see if a person has had multiple names
# IE change maiden to married, etc - method to check for name changes via marriage or divorce
name_data <- sqlQuery(squibbs, "( SELECT 
  n.ID_NUMBER ,n.XSEQUENCE ,n.NAME_TYPE_CODE ,n.PREF_NAME ,n.REPORT_NAME ,n.XCOMMENT
  ,n.LAST_NAME ,n.FIRST_NAME ,n.MIDDLE_NAME ,n.PREFIX ,n.PERS_SUFFIX ,n.PROF_SUFFIX
  ,n.DATE_ADDED ,n.DATE_MODIFIED ,n.OPERATOR_NAME

  --,n.SALUTATION ,n.ORG_LONG_NAME1 ,n.ORG_LONG_NAME2 ,n.NAME_SOUNDEX ,n.LOOKUP_LAST_NAME
  --,n.USE_FOR_TAX_RECEIPT_IND ,n.LOOKUP_FIRST_NAME ,n.LOOKUP_MIDDLE_NAME ,n.TENTCARD_NAME ,n.NAMETAG_NAME 
  --,n.USER_GROUP ,n.DATA_SOURCE_CODE ,n.LOCATION_ID ,n.FIRST_NAME_SOUNDEX ,n.MIDDLE_NAME_SOUNDEX
  FROM advance.name n)")

email_DATE <- sqlQuery(squibbs, "( SELECT
  em.ID_NUMBER ,em.XSEQUENCE ,em.EMAIL_TYPE_CODE ,em.EMAIL_STATUS_CODE
  ,em.EMAIL_ADDRESS ,em.PREFERRED_IND ,em.STATUS_CHANGE_DATE ,em.XCOMMENT 
  ,em.START_DT ,em.STOP_DT ,em.DATE_ADDED ,em.DATE_MODIFIED
  ,em.IMODULES_IND ,em.NBR_BOUNCEBACKS ,em.OPERATOR_NAME 
  --,em.USER_GROUP ,em.LOCATION_ID ,em.EMAIL_CODE ,em.EMAIL_FORMAT_CODE 
  --,em.FORWARDS_TO_EMAIL_ADDRESS ,em.ORIGINAL_SOURCE_CODE ,em.CHANGE_SOURCE_CODE 
  --,em.CHANGE_SOURCE_DATE ,em.FAILED_REASON_CODE 
  FROM advance.email em ")
